version: '2.0'
services:
  workerL:
    #image: morse-stf:v0.3
    image: morse-stf:ceping
    #image: morse-registry.cn-shanghai.cr.aliyuncs.com/rd/morse-stf:test20220606
    #image: registry.cn-hangzhou.aliyuncs.com/dtunion/morseredis:v24
    ports:
      - 7777:7777
    cap_add:
      - ALL
    tty: true

    #stdin_open: true
    volumes:
    # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    #  - /Users/qizhi.zqz/projects/morse-stf/morse-stf/conf:/morse-stf/conf
    #  - /Users/qizhi.zqz/projects/morse-stf/morse-stf/dataset:/morse-stf/dataset
     - /root/qizhi.zqz/morse-stf/dataset:/morse-stf/dataset
     - /root/qizhi.zqz/morse-stf/conf:/morse-stf/conf
    command:
        morse-stf-server --player=workerL  --config_file=/morse-stf/conf/config_epsilon2.json
        #wondershaper eth0 10240 10240
  workerR:
    image: morse-stf:ceping
    ports:
    - 7777:7777
    cap_add:
      - ALL
    tty: true
    #stdin_open: true
    volumes:
    # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
     - /root/qizhi.zqz/morse-stf/dataset:/morse-stf/dataset
     - /root/qizhi.zqz/morse-stf/conf:/morse-stf/conf
    command:
#      - /bin/bash
#      - -c
#      - |
        morse-stf-server --player=workerR  --config_file=/morse-stf/conf/config_epsilon2.json
        #wondershaper eth0 10240 10240
  RS:
    image: morse-stf:ceping
    ports:
      - 7777:7777
    cap_add:
      - ALL
    tty: true
    #stdin_open: true
    volumes:
    #- /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    #- /Users/qizhi.zqz/projects/TFE/tf-encrypted/examples/test_on_morse_datas/data:/morse-stf/data
     - /root/qizhi.zqz/morse-stf/dataset:/morse-stf/dataset
     - /root/qizhi.zqz/morse-stf/conf:/morse-stf/conf
    command: morse-stf-server --player=RS  --config_file=/morse-stf/conf/config_epsilon2.json


#networks:
#  counter-net:
#
#volumes:
#  counter-vol:

#docker exec -it  xxx  wondershaper eth0 10240 10240